ip: 192.168.4.18
port: 16171
velocity_covariance: [0, 0, 0, 0, 0, 0, 0, 0, 0]
positoin_covariance: [0, 0, 0, 0, 0, 0, 0, 0, 0]
speed_of_sound: 1500
mounting_rotation_offset: 0
acoustics_enabled: false