# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ feature-github-actions ]
  pull_request:
    branches: [ feature-github-actions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: noetic

      - name: Install required packages
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          source /opt/ros/noetic/setup.bash
          rosdep update
          mkdir -p ~/catkin_ws/src
          cp -r $GITHUB_WORKSPACE ~/catkin_ws/src/$REPO_NAME
          cd ~/catkin_ws
          rosdep install --from-paths src --ignore-src -r -s  # do a dry-run first
          rosdep install --from-paths src --ignore-src -r -y

      - name: catkin build
        run: |
          source /opt/ros/noetic/setup.bash
          cd ~/catkin_ws
          catkin_make -DCMAKE_BUILD_TYPE=Release
          source devel/setup.bash